version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: "unless-stopped"
    ports: 
      - "4001:3000"
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public